In [2]:
import numpy as np

# ймовірність виявлення стандартної деталі
p_standard = 0.6

# кількість деталей, які підлягають перевірці
n = 3

# створюємо можливі значення випадкової величини X - кількість бракованих деталей
x_values = np.arange(0, n+1)

# обчислюємо ймовірності відповідних значень X
p_x = [np.math.comb(n, x) * (1 - p_standard)**x * p_standard**(n-x) for x in x_values]

# створюємо можливі значення випадкової величини Y - кількість стандартних деталей
y_values = np.arange(0, n+1)

# обчислюємо ймовірності відповідних значень Y
p_y = [np.math.comb(n, y) * p_standard**y * (1 - p_standard)**(n-y) for y in y_values]


In [4]:
# створюємо таблицю ймовірностей спільних значень (X,Y)
joint_probs = np.zeros((n+1, n+1))
for x in x_values:
    for y in y_values:
        if x+y <= n:
            joint_probs[x,y] = np.math.comb(n, x) * p_standard**y * (1 - p_standard)**(n-x-y) * (1 - p_standard)**x

In [5]:
# обчислюємо коефіцієнт кореляції
covariance = np.sum((x_values[:,np.newaxis]-np.mean(x_values))*(y_values[np.newaxis,:]-np.mean(y_values))*joint_probs)
std_x = np.sqrt(np.sum((x_values-np.mean(x_values))**2 * p_x))
std_y = np.sqrt(np.sum((y_values-np.mean(y_values))**2 * p_y))
correlation = covariance / (std_x * std_y)

In [6]:
print("Закон розподілу випадкової величини X:\n", x_values)
print("Ймовірності відповідних значень X:\n", p_x)
print("Закон розподілу випадкової величини Y:\n", y_values)
print("Ймовірності відповідних значень Y:\n", p_y)
print("Таблиця спільних йможливих значень (X,Y):\n", joint_probs)
print("Коефіцієнт кореляції r(X,Y) = ", correlation)

Закон розподілу випадкової величини X:
 [0 1 2 3]
Ймовірності відповідних значень X:
 [0.21599999999999997, 0.43200000000000005, 0.28800000000000003, 0.06400000000000002]
Закон розподілу випадкової величини Y:
 [0 1 2 3]
Ймовірності відповідних значень Y:
 [0.06400000000000002, 0.28800000000000003, 0.43200000000000005, 0.21599999999999997]
Таблиця спільних йможливих значень (X,Y):
 [[0.064 0.096 0.144 0.216]
 [0.192 0.288 0.432 0.   ]
 [0.192 0.288 0.    0.   ]
 [0.064 0.    0.    0.   ]]
Коефіцієнт кореляції r(X,Y) =  -0.7777777777777776
